### ISSUE TITLE
Master/dev builds don't quite work

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#126]
In my latest PR the master/dev build fails with a conflicted environment.

The dev test works by using `pcds-dev` as the first channel, so it's probably one of the following things:
- Tags don't exist on `pcds-dev`, so when the dev channel is used, a minimum tag is required, and at least one packages has no PRs from after the most recent tag, it's possible that there isn't a way to satisfy the dependency.
- Since we've put packages onto `conda-forge` and the dev test works by using `pcds-dev` as the first channel, and since the recipe in each repo that gets uploaded to `pcds-dev` is not necessarily the same as the one on `conda-forge`, the dev build doesn't behave the same way as the tag build will. (E.g. at least one of our internally used recipes are broken)

**Comment by hhslepicka** [comment]
Once we move to the usage of the pcds-ci-helpers it will also address this issue since it uploads to both pcds-dev and pcds-tag... conda-forge is the same as pcds-tag...
