### ISSUE TITLE
Update matplotlib

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#137]
Currently stuck at old version for some reason
Try to update and investigate which packages (if any) are holding us back

**Comment by ZLLentz** [comment]
`pcdsdevices` and `pcdsdaq` both specify `matplotlib<3`

**Comment by ZLLentz** [comment]
`pcdsdaq` no longer has a `matplotlib` dependency

**Comment by ZLLentz** [comment]
closed accidentally in #161

**Comment by klauer** [comment]
Accidentally closed as in "oops, I fixed it"?

**Comment by ZLLentz** [comment]
I did not intend to fix it during that PR, but that PR did fix it, and I did not notice it was fixed until today
