### ISSUE TITLE
DAQ fails to load in pcds-4.0.0

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#170]
Undefined symbol PyString_AsString on pydaq import on xpp-control
https://pswww.slac.stanford.edu/lgbk/lgbk/XPP_Instrument/ws/attachment?entry_id=602c8d590da85419e8f64c1f&attachment_id=602c8d590da85419e8f64c1c&prefer_preview=False

**Comment by klauer** [comment]
`PyString_AsString` is Python 2 API: 

https://docs.python.org/2.7/c-api/string.html
> Note: These functions have been renamed to PyBytes_* in Python 3.x. Unless otherwise noted, the PyBytes functions available in 3.x are aliased to their PyString_* equivalents to help porting. 

Aliases may have been removed in 3.8, breaking the DAQ?

New:
https://docs.python.org/3/c-api/bytes.html#c.PyBytes_AsString

**Comment by ZLLentz** [comment]
Works fine on `psbuild-rhel7-01`, which imports latest `pydaq`. Hypothesis is that xpp's daq sym link is outdated, will investigate.

**Comment by ZLLentz** [comment]
Seems like a bingo:
```
(pcds)zlentz@psbuild-rhel7-01:.../dist/pds$ pwd
/cds/group/pcds/dist/pds
(pcds)zlentz@psbuild-rhel7-01:.../dist/pds$ ll | grep current
lrwxrwxrwx 1 psreldev ps-pcds        19 Dec 18 16:47 ami-current -> ./ami-8.11.0-p9.1.0
lrwxrwxrwx 1 psreldev ps-pcds        15 Dec 18 17:25 current -> ./10.2.4-p9.1.0
(pcds)zlentz@psbuild-rhel7-01:.../dist/pds$ ll xpp | grep current
lrwxrwxrwx 1 xppopr   ps-pcds   15 Nov  8 12:13 ami-current -> ami-current-dev
lrwxrwxrwx 1 xppopr   ps-pcds   20 Dec  3 14:34 ami-current-dev -> ../ami-8.10.6-p9.1.0
lrwxrwxrwx 1 xppopr   ps-pcds   20 Dec  3 14:34 ami-current-sav -> ../ami-8.10.4-p9.0.3
lrwxrwxrwx 1 xppopr   ps-pcds   11 Aug 12  2020 current -> current-dev
lrwxrwxrwx 1 xppopr   ps-pcds   17 Oct  3 00:02 current-dev -> ../10.2.0-p9.1.0/
-rw-r--r-- 1 xppopr   ps-pcds  949 Jan  3  2019 .current_history
lrwxrwxrwx 1 xppopr   ps-pcds   17 Oct  3 00:01 current-sav -> ../10.1.8-p9.0.3/
```

**Comment by klauer** [comment]
That's a relief! 👏

**Comment by ZLLentz** [comment]
Seems to be resolved
