### ISSUE TITLE
pcdswidgets are missing from designer in pcds-4.0.0

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#172]
Works in pcds-3.5.0 with pcdswidgets=0.4.2, python=3.6
Fails in pcds-4.0.0 with pcdswidgets=0.5.1, python=3.8
Works in current dev pcdswidgets=0.4.2, python=3.6

**Comment by ZLLentz** [comment]
Fails on my test env with pcdswidgets=0.4.2, python=3.8

**Comment by ZLLentz** [comment]
Ok all of that was a red herring, this is an issue with our conda-forge recipe. We need to edit that to use the special build.sh script just like the pcds-tag recipe.

**Comment by klauer** [comment]
Activation scripts, ugh. This is one reason I was hoping to push this alternative that never took off: https://github.com/pcdshub/pyqt-designer-plugin-entry-points

**Comment by ZLLentz** [comment]
Ahh, I either forgot about or never saw that. I agree with the concept, entry points are waaaay better than stashing this in the conda recipe- not only because it's easy to break things, but also because the currently solution makes the pypi builds not able to use designer in the proper way.

**Comment by ZLLentz** [comment]
I am going to make:
- Issues on pcdswidgets and typhos about using pyqt-designer-plugin-entry-points
- A PR on pcdswidgets-feedstock, incrementing the build number and adding an appropriate bash build script
