### ISSUE TITLE
databroker broken in pcds-4.0.0?

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-envs#174]
databrok~en~er
See: https://gist.github.com/klauer/f9b6a8b2869df85abe7368f4f6d12e4e

Seems like we need `bluesky-live`

**Comment by klauer** [comment]
This isn't really our fault, for what it's worth: 

https://github.com/conda-forge/databroker-feedstock/issues/27
And https://github.com/conda-forge/staged-recipes/pull/14055

**Comment by ZLLentz** [comment]
interesting

**Comment by ZLLentz** [comment]
We'll wait for the bluesky-live conda-forge, but in the future we can also just add it to the pip installs if something like this is a blocker

**Comment by klauer** [comment]
Now on conda-forge: https://github.com/conda-forge/bluesky-live-feedstock

**Comment by ZLLentz** [comment]
I think we manually add bluesky-live for now?

**Comment by klauer** [comment]
Yeah, seems reasonable to add it manually for now while their recipe is broken.
