### ISSUE TITLE
Add bluesky-widgets, bluesky-widgets-demo

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#224]
For use in the queueserver-related guis

**Comment by ZLLentz** [comment]
Currently these are run using fraken-dev sorts of clones for UED, but this needs to be reworked and the proper packages should be included in the environment.

**Comment by klauer** [comment]
It's a bit weird that we rely on bluesky-widgets-demo; I wonder if we should be forking/reimplementing/renaming it?

**Comment by ZLLentz** [comment]
Ah yeah the way it's set up was "do it fast", so it's actually using a combination of both a forked `bluesky-widgets-demo` and `bluesky-widgets`

It should really be:
- using none of `bluesky-widgets-demo`
- extending `bluesky-widgets` itself without forking it
- setting up its own launcher

**Comment by ZLLentz** [comment]
bluesky-widgets is installed, I'm going to leave out bluesky-widgets-demo because it'll cause more issues than it will help to add it here
