### ISSUE TITLE
Evaluate memray and consider adding it to our environment

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-envs#229]
Link: https://github.com/bloomberg/memray

> Memray is a memory profiler for Python. It can track memory allocations in Python code, in native extension modules, and in the Python interpreter itself. It can generate several different types of reports to help you analyze the captured memory usage data. While commonly used as a CLI tool, it can also be used as a library to perform more fine-grained profiling tasks.

**Comment by ZLLentz** [comment]
memray dependencies from conda search --info memray:
```
  - jinja2
  - libgcc-ng >=10.3.0
  - libstdcxx-ng >=10.3.0
  - libunwind >=1.6.2,<1.7.0a0
  - python >=3.9,<3.10.0a0
  - python_abi 3.9.* *_cp39
  - rich <11.0.0
```
All of these are already installed in pcds-5.3.1

Chicken and egg: do we install first for the start of May tag and evaluate after? Or let this sit another cycle?

**Comment by ZLLentz** [comment]
Backtracking a bit: `rich` actually isn't installed, which confuses me. I wonder if we have a library that forgot to add it as a dependency, or if none of those got tagged yet.

**Comment by klauer** [comment]
Hmm, atef is the only one that uses rich so far, probably. I should probably make an issue for adding it to the environment..
