### ISSUE TITLE
Verify compatibility with pyqt 5.15

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-envs#233]
It was just released on conda-forge - but it's not clear if it's going to break things for us or make things better.

We may need to add `qt-webengine` as a dependency, and follow up with the conda-forge newsletter indicating about further changes.

**Comment by ZLLentz** [comment]
The PyDM test suite seems to have issues on appveyor with 5.15- might be enough reason to hold back. Not fully confirmed until the CI on https://github.com/slaclab/pydm/pull/849 runs.
