### ISSUE TITLE
Add deploy script for cleaning up old hard drive conda envs

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#243]
A few of the hosts are starting to fill up on disk space from the on-disk conda releases

We need to write a script that:
- checks what version the hutch is running
- keeps the most recent versions and n versions prior to the active version
- deletes everything else older

for some n that we should agree on

**Comment by ZryletTC** [comment]
If it helps at all, I usually use an alias of `grep --color=auto CONDA_ENVNAME= /reg/g/pcds/pyps/apps/hutch-python/*/*env | grep -v "#" | sed -n 's/.*hutch-python\/\(.*\)\/.*"\(.*\)"/\1\t\2/p'` to check all hutches.
Modifying/simplifying it for one hutch would be `grep CONDA_ENVNAME= /reg/g/pcds/pyps/apps/hutch-python/${hutch}/${hutch}env | grep -v "#" | sed -n 's/.*"\(.*\)"/\1/p'`.
If you already have code for this, please ignore :)

**Comment by ZLLentz** [comment]
I did not already have code for this! Thank you very much for the helpful snippit!
