### ISSUE TITLE
Addition of Qt debug tool GammaRay (dev? prod?)

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-envs#245]
## What is it?

Documentation: https://doc.qt.io/GammaRay/index.html

> [GammaRay](http://doc.qt.io/GammaRay) is an introspection tool for Qt applications developed by [KDAB](https://www.kdab.com/). Leveraging the [QObject](http://doc.qt.io/qt-5/qobject.html) introspection mechanism it allows you to observe and manipulate your application at runtime. This works both locally on your workstation and remotely on an embedded target.

## Feedstock

https://github.com/conda-forge/gammaray-feedstock

## Possible issue

Adding it to the production environment may be problematic once we reach Qt 5.15 as the feedstock build is failing. Based on the two unmerged PRs in that repository, it does not appear that the repository is actively maintained.

So - possibly this could be a dev-env (or temporary prod) addition while it works with our installed Qt version.

**Comment by ZLLentz** [comment]
I'm happy to add this to prod and make it dev-only later if need be. It seems like a useful tool and I don't expect anyone to import it in a different tool.
