### ISSUE TITLE
Identify "interactive-only" packages to freeze versions of

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#248]
Packages like IPython that primarily present themselves as interactive interfaces are difficult to test automatically for compatibility with user operations at SLAC/LCLS. Bugs and new behavior easily slip through unnoticed as the library continues to improve its user experience.

Need to:
- lock the version of IPython and upgrade only very deliberately
- identify other packages that may need the same treatment

**Comment by tangkong** [comment]
I imagine pyqt / qtpy is another candidate for freezing.  We've already frozen it due to CI bugs, but maybe we should make that the norm rather than the exception
