### ISSUE TITLE
Request to add laserbeamsize package

### ISSUE THREAD

**Issue by efcunn** [pcdshub/pcds-envs#267]
Hello -- This is a request to add the laserbeamsize package to our standard Python environment https://pypi.org/project/laserbeamsize/ . This package comes highly recommended from our counterparts in the laser delivery group at the European XFEL as a way of facilitating and standardizing laser beam size measurements, which are an important part of optical laser operations at LCLS as well. Please let me know if you have any questions. Thanks! ~Eric

**Comment by ZLLentz** [comment]
Package looks good to me. We already have all the dependencies installed.

Dependencies for reference: https://github.com/scottprahl/laserbeamsize/blob/master/requirements.txt

I'll put this in the new year conda env too

**Comment by efcunn** [comment]
That's awesome, thank you again for your help Zach!
