### ISSUE TITLE
Add dependencies from pcds-python-migration-tools

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-envs#273]
## pcds-python-migration-tools support

I was running our repository migrations locally, so there are a couple dependencies that aren't in our pcds-envs.

Requirements file:

https://github.com/pcdshub/pcds-python-migration-tools/blob/master/requirements.txt

We'll need at least these:
* pyupgrade
* pycln

Looks like our pre-commit version is quite old and we should consider upgrading it, too

**Comment by ZLLentz** [comment]
it might make sense to go back to always-update mode for all the linting/checking packages (flake8, pre-commit, ...)

**Comment by ZLLentz** [comment]
the current way we run with "minimize updates" is mostly intended for runtime dependencies, e.g. ipython, pyqt

**Comment by klauer** [comment]
I think that would make sense, @ZLLentz, to automatically update those 👍
