### ISSUE TITLE
Add hklpy [LCLSECSD-2017]

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-envs#275]
Add the hklpy library:
* Feedstock: https://github.com/conda-forge/hklpy-feedstock
* Source: https://github.com/bluesky/hklpy
* Diffractometer computation library with ophyd pseudopositioner support 

cc @jyotiphy

**Comment by jyotiphy** [comment]
https://jira.slac.stanford.edu/browse/LCLSECSD-2017
