### ISSUE TITLE
Add pytest-asyncio

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#281]
This is used by atef as a test dependency

**Comment by tangkong** [comment]
Hopefully by then we can also just add atef 😬

**Comment by ZLLentz** [comment]
Typically the conda builds don't have the test requirements so I think it's good to include this explicitly anyway!

**Comment by klauer** [comment]
Since we started to add test requirements to our conda recipes, would a script to aggregate all of those for the purposes of pcds-envs be a good idea? (Or any better ideas?)

**Comment by ZLLentz** [comment]
Would it be easier to do this by looking at the (installed? desired?) recipes and scraping out the test section or would it be easier to include a "clone and check dev-requirements.txt" step?

I'm moderately surprised there's no "conda install --include-test-deps"

**Comment by klauer** [comment]
> Would it be easier to do this by looking at the (installed? desired?) recipes and scraping out the test section 

This is the only valid way if we want to install the test dependencies through conda, which would reflect what we do in CI conda jobs

> or would it be easier to include a "clone and check dev-requirements.txt" step?

That'd be a lot easier - if we're OK with installing from PyPI and knowing that what we get might differ from conda

> I'm moderately surprised there's no "conda install --include-test-deps"

Same!
