### ISSUE TITLE
ADD: `pytest-cov`

### ISSUE THREAD

**Issue by tangkong** [pcdshub/pcds-envs#292]
I was trying to run pytest in our pcds-conda env with the coverage argument added to `pyproject.toml`, and pytest errors out if `pytest-cov` is not found.  

I got around this for the moment via venv shadowing, but I figure if we proliferate this and want other people to run the test suite we should add it.  

It was surprising to me that a minimal `pytest` invocation grabbed the additional option information from `pyproject.toml`, maybe I have something set up weird?

**Comment by klauer** [comment]
> It was surprising to me that a minimal `pytest` invocation grabbed the additional option information from `pyproject.toml`, maybe I have something set up weird?

That's intentional. If you run `pytest` you're supposed to have `dev-requirements`

**Comment by ZLLentz** [comment]
I think it does make sense to include pytest-cov in the env
Still looking for ways to say "include all test dependencies from the conda recipes" more generically

**Comment by ZLLentz** [comment]
Would it be dumb to write a script that accumulates all the dev- and doc- requirements from all pcds/ecs dependencies and include them in the env by default?

**Comment by klauer** [comment]
I think that's a good idea
