### ISSUE TITLE
package request: pynput

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#296]
or: a library for reliably getting user mouse/keyboard inputs
requested by James Cryan via slack in the hutch-python channel
https://pypi.org/project/pynput/

**Comment by klauer** [comment]
We do this in pcdsdevices for moving motors, don't we? And matplotlib for grabbing a specific position on a plot?

To what end does James want keyboard/mouse input?

**Comment by ZLLentz** [comment]
we use a matplotlib built-in for picking the plot point by click and we switch the input mode for the motor arrows

I can revisit and ask James what exactly he's cooking

**Comment by ZLLentz** [comment]
I'm hesitant to include this because it's not actively maintained and isn't packaged as compatible with python 3.10+, I'm going to quietly close the issue and if it comes up again we'll revisit other options for input
