### ISSUE TITLE
whatrecord, epicsmacrolib are now on conda-forge

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-envs#299]
Now that these are on conda-forge:
https://github.com/conda-forge/whatrecord-feedstock/
https://github.com/conda-forge/epicsmacrolib-feedstock/

I think we can point the environment building process to those instead of PyPI at some point

**Comment by ZLLentz** [comment]
Great news!
I'll switch them over for the next tag, which will either be the dreaded py3.10 tag or I'll chicken out
