### ISSUE TITLE
pcaspy

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcds-envs#31]
Attn: @hhslepicka

**Comment by hhslepicka** [comment]
Justification:
PyDM uses pcaspy for the testing-ioc which is only useful for the examples.
Users that try to get the examples going will need to create a custom environment just because of pcaspy if it is not present on the current environment.

**Comment by ZLLentz** [comment]
I'm loathe to expand the channels list any further, so to do this I'm finally going to buckle down and build/include all of these extra packages in `pcds-tag`, then add `pcaspy` and shrink our channel list down to just `defaults`, `conda-forge`, and `pcds-tag`.

**Comment by teddyrendahl** [comment]
Why would you name your channel `paulscherrerinstitute` so long! Thats like naming ours `photoncontrolsanddatasystems`

**Comment by ZLLentz** [comment]
`slaclinearacceleratorcenterlinaccoherentlightsourcephotoncontrolsanddatasystems`

**Comment by hhslepicka** [comment]
Thank you @ZLLentz ! 🎉
