### ISSUE TITLE
Pydm plugins fix missing from deploy step

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#311]
it's a long story

```
zlentz@psbuild-rhel7-01:.../py39/envs$ chmod u+w pcds-5.8.1/plugins/designer/
zlentz@psbuild-rhel7-01:.../py39/envs$ cp pcds-5.7.3/plugins/designer/libpyqt5.so pcds-5.8.1/plugins/designer/
```

**Comment by tangkong** [comment]
This has been broken for quite some time now ([conda-forge issue by our some of our own](https://github.com/conda-forge/pyqt-feedstock/issues/113)), we'll probably have to do this ourselves for a while.
