### ISSUE TITLE
Cannot display plots with Matplotlib.pyplot 

### ISSUE THREAD

**Issue by apra93** [pcdshub/pcds-envs#32]
## Expected Behavior

Entering `plt.plot(range(100))` should create an object that can then be plotted using `plt.show()`

## Current Behavior

It first spits out an error, and then causes the `ipython` session to hang when you run the `plt.show()` command.

## Steps to Reproduce (for bugs)

```
(pcds-0.6.1) xcs-console:snd> ipython
Python 3.6.4 |Anaconda, Inc.| (default, Mar 13 2018, 01:15:57) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib.pyplot as plt

In [2]: plt.plot(list(range(100)))
QFontDatabase: Cannot find font directory /reg/g/pcds/pyps/conda/py36/envs/pcds-0.6.1/lib/fonts - is Qt installed correctly?
QFontDatabase: Cannot find font directory /reg/g/pcds/pyps/conda/py36/envs/pcds-0.6.1/lib/fonts - is Qt installed correctly?
QFontDatabase: Cannot find font directory /reg/g/pcds/pyps/conda/py36/envs/pcds-0.6.1/lib/fonts - is Qt installed correctly?
QFontDatabase: Cannot find font directory /reg/g/pcds/pyps/conda/py36/envs/pcds-0.6.1/lib/fonts - is Qt installed correctly?
Out[2]: [<matplotlib.lines.Line2D at 0x7f8a9415c0b8>]

In [3]: plt.show()
This plugin does not support propagateSizeHints()
This plugin does not support raise()


```
## Context

Was trying to create a method that would plot a dataframe, but found I couldn't on `pcds-0.3.0` or `pcds-0.6.1`.

## Your Environment

As mentioned above this was done using `pcds-0.3.0` or `pcds-0.6.1`, as `apra`, `xcsopr`, and `sxropr`, on `psbuild-rhel7-02` and `xcs-console`.

**Comment by ZLLentz** [comment]
Have you tried using the `%matplotlib qt` magic command?

**Comment by teddyrendahl** [comment]
I went through this battle with @rajanplumley earlier this week. The Qt stuff is super sensitive to strange things in bashrc. 

I do think however this is what @ZLLentz mentioned. The `hutch-python` startup automatically does this for you but it is honestly such a universal thing that we should find a place for it in documentation.  Also frustrating that `matplotlib` doesn't catch this kind of stuff nicely.

**Comment by teddyrendahl** [comment]
Made a PR https://github.com/pcdshub/pcdshub.github.io/pull/6 with what I know of know is necessary to setup everything up in your own IPython shell. If it is one of these issues we'll merge but if it isn't we'll have something new to add. 😅

**Comment by teddyrendahl** [comment]
Closing this unless we hear back that we misdiagnosed the issue.
