### ISSUE TITLE
Add shapely package

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/pcds-envs#331]
The lasers group would like to have the shapely package added to our environment to aid in beam profile analysis. 

https://pypi.org/project/shapely/

**Comment by ZLLentz** [comment]
Available on conda-forge, should be straightforward

- Package seems mature and actively maintained
- Has builds for py3.9, 3.10, 3.11, 3.12
- Dependencies are:
```
shapely 2.0.4 py39h6404dd3_0
----------------------------
file name   : shapely-2.0.4-py39h6404dd3_0.conda
name        : shapely
version     : 2.0.4
build       : py39h6404dd3_0
build number: 0
size        : 469 KB
license     : BSD-3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/shapely-2.0.4-py39h6404dd3_0.conda
md5         : c33c60a88dad5df6960c4da482f9e313
timestamp   : 2024-04-17 09:31:07 UTC
dependencies:
  - geos >=3.12.1,<3.12.2.0a0
  - libgcc-ng >=12
  - numpy >=1.22.4,<2.0a0
  - python >=3.9,<3.10.0a0
  - python_abi 3.9.* *_cp39

geos 3.12.1 h59595ed_0
----------------------
file name   : geos-3.12.1-h59595ed_0.conda
name        : geos
version     : 3.12.1
build       : h59595ed_0
build number: 0
size        : 1.7 MB
license     : LGPL-2.1-only
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/geos-3.12.1-h59595ed_0.conda
md5         : 8c0f4f71f5a59ceb0c6fa9f51501066d
timestamp   : 2023-11-12 08:35:02 UTC
dependencies:
  - libgcc-ng >=12
  - libstdcxx-ng >=12
```

**Comment by aberges-SLAC** [comment]
Hey @ZLLentz as this is going to be necessary for the MODS TILE GUI OIP that Ebram is working on, and TMO in particular is eager to get access to the GUI, it'd be nice to have this module in the next pcds-conda release.

Anything I can do to help?

**Comment by ZLLentz** [comment]
A few options:

- We can create a dev release that has shapely
- We can create a new tag that only has shapely added
- We can do a full tag release (write documentation/tag every package and work through any new conflicts)

**Comment by aberges-SLAC** [comment]
Lets do a dev release for now just get to test in a few areas once some refactoring happens, although I imagine if it goes well with the end users it will roll out to more areas and likely warrant a full tag release.

@slactjohnson Thoughts?

**Comment by slactjohnson** [comment]
@aberges-SLAC I think a dev release is fine, as that would allow you to continue your work. We can swap to the prod release, whenever it occurs. I don't see a reason to incur ~1 day of work for just a single package.

**Comment by aberges-SLAC** [comment]
Agreed! Thank you both very much @slactjohnson @ZLLentz :]

**Comment by ZLLentz** [comment]
I made a lightweight venv whose activation script is at `/cds/group/pcds/pyps/conda/venvs/shapely/bin/activate`. This is simply a shapely pip installed on top of the base pcds-5.8.4.
