### ISSUE TITLE
Packages for Mike

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#34]
"Aside from the aforementioned patch to PyQt5, I also need additions to your standard environment:
pip install ConfigParser
pip install mysqlclient
conda install mysql=5.5.24
"

**Comment by teddyrendahl** [comment]
`configparser` is still in standard lib just renamed. Tell him to just use:

```python
try:
    import ConfigParser
except ImportError:
    import configparser as ConfigParser
```

**Comment by ZLLentz** [comment]
Yep, already told him, just didn't feel like changing the paste from his email
