### ISSUE TITLE
PYQTDESIGNERPATH Conflicts

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcds-envs#82]
Something in the latest installation has kicked `PyDM` widgets out of the `PYQTDESIGNERPATH`. The `typhon` path is properly inserted. This may be an issue with `typhon` itself.

**Comment by hhslepicka** [comment]
Which PyDM version? Also, do you mind to add here your `PYQTDESIGNERPATH` ? Maybe it can shine some light...

**Comment by teddyrendahl** [comment]
Reported `PYQTDESIGNERPATH`:

`/reg/g/pcds/pyps/conda/py36/envs/pcds-2.1.0/etc/typhon:`

Relevant Packages
```
typhon                    0.3.0                    py36_0    pcds-tag
pydm                      1.6.5                    py36_1    pcds-tag
```

**Comment by hhslepicka** [comment]
Mind to check if you have a `$PREFIX/etc/conda/activate.d/pydm.sh` ?
And also `$PREFIX/etc/pydm`...

**Comment by teddyrendahl** [comment]
```
$ ls $CONDA_PREFIX/etc/pydm
designer_plugin.py  __pycache__
```
```
$ cat $CONDA_PREFIX/etc/conda/activate.d/pydm.sh 
export PYQTDESIGNERPATH=/reg/g/pcds/pyps/conda/py36/envs/pcds-2.1.0/etc/pydm:
```

**Comment by teddyrendahl** [comment]
looks like there is a bug in both and Typhon just ran last? Those `activate.d` scripts will fight each other...
```
$ cat $CONDA_PREFIX/etc/conda/activate.d/typhon.sh 
export PYQTDESIGNERPATH=/reg/g/pcds/pyps/conda/py36/envs/pcds-2.1.0/etc/typhon:
export PYDM_DESIGNER_ONLINE=True
```

**Comment by hhslepicka** [comment]
Yeah, that is correct. We need to find a way to delay the expansion of the `$PYQTDESIGNERPATH` until the script is executed. We need to escape the string at the `build.sh` for both...

**Comment by teddyrendahl** [comment]
I think we can do something simpler. If both end-up with the following they won't fight each other

`export $PYQTDESIGNERPATH=path/to/designer_plugin:$PYQTDESIGNERPATH`

The only issue is this won't clear out anything you had set in this variable before activating the environment

**Comment by hhslepicka** [comment]
Not sure if I am following... I will ping you at SLACK.

**Comment by teddyrendahl** [comment]
https://github.com/pcdshub/pcds-recipes/pull/32
https://github.com/pcdshub/typhon/pull/203
https://github.com/slaclab/pydm/pull/502
