### ISSUE TITLE
pytmc tests pass without the required dependencies

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#92]
The most recent environment should have failed at travis because we were missing `epics-pypdb`. I'm not sure if `pytmc` doesn't sufficiently check for this or if the tests run oddly because we're doing them in bulk.

See https://travis-ci.org/pcdshub/pcds-envs/jobs/622403674#L3101

Most likely candidate:
```
SKIP [1] tests/test_commandline.py: got empty parameter set ['project_filename'], function test_summary at /home/travis/build/pcdshub/pcds-envs/pytmc/tests/test_commandline.py:27

SKIP [1] tests/test_commandline.py: got empty parameter set ['project_filename'], function test_pragmalint at /home/travis/build/pcdshub/pcds-envs/pytmc/tests/test_commandline.py:40

SKIP [1] tests/test_commandline.py: got empty parameter set ['project_filename'], function test_stcmd at /home/travis/build/pcdshub/pcds-envs/pytmc/tests/test_commandline.py:46

SKIP [1] tests/test_commandline.py: got empty parameter set ['project_filename'], function test_xmltranslate at /home/travis/build/pcdshub/pcds-envs/pytmc/tests/test_commandline.py:56

SKIP [1] tests/test_motion.py: got empty parameter set ['project_filename'], function test_motion_stcmd at /home/travis/build/pcdshub/pcds-envs/pytmc/tests/test_motion.py:4

SKIP [1] tests/test_project.py: got empty parameter set ['project_filename'], function test_load_and_repr at /home/travis/build/pcdshub/pcds-envs/pytmc/tests/test_project.py:6

SKIP [1] tests/test_project.py: got empty parameter set ['project_filename'], function test_summarize at /home/travis/build/pcdshub/pcds-envs/pytmc/tests/test_project.py:11

SKIP [1] tests/test_project.py: got empty parameter set ['project_filename'], function test_module_ads_port at /home/travis/build/pcdshub/pcds-envs/pytmc/tests/test_project.py:24

SKIP [1] tests/test_project.py:30: got empty parameter set ['project_filename'], function test_smoke_ams_id at /home/travis/build/pcdshub/pcds-envs/pytmc/tests/test_project.py:29

SKIP [1] tests/test_project.py: got empty parameter set ['project_filename'], function test_fb_motionstage_linking at /home/travis/build/pcdshub/pcds-envs/pytmc/tests/test_project.py:35
```

**Comment by ZLLentz** [comment]
Any insight on this one @klauer @n-wbrown?

My environment broke on pytmc despite my integration tests passing.

**Comment by klauer** [comment]
I think it's because you're not doing a recursive checkout, so there are no projects to lint. It's a bit unexpected, but not so concerning in my opinion.

**Comment by ZLLentz** [comment]
Recursive checkouts solved the skipping, but all of these skipped tests pass without the dependency

**Comment by ZLLentz** [comment]
Tests are passing because we provide `pypdb` from https://anaconda.org/pcds-tag/pypdb via https://github.com/pcdshub/pcds-recipes/blob/master/pypdb/meta.yaml and the `pytmc` recipe specifies `pypdb` as a requirement.

So the real issue is figuring out why the deployed environment didn't work until I pip installed `epics-pypdb`... The tests were always set to catch the missing module.

Long term I need to nuke those `pypdb` `pcds-tag` entries due to the naming conflict
